mutation ReceiveTicketFree($input: TicketFreeMutationInput!) {
    receiveTicketFree(input: $input) {
        ...TodayGift
        __typename
    }
}

fragment TodayGift on TodayGift {
    id
    uid
    ticketType
    ticketKind
    ticketCount
    ticketExpireAt
    ticketExpiredText
    isReceived
}
